---
pdos:

 - 
    - addr: 0x1600
      type: rx
    -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
    -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e

 - 
    - addr: 0x1601
      type: rx  
    -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
    -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e

...
---

pdo_mapping_1:
 addr: 0x1600
 type: rx

 pdos:
  -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
  -
    name: a
    index: b
    subindex: c
    bitlength: d
    type: e

pdo_mapping_2:
 addr: 0x1601
 type: rx

 pdos:
  -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
  -
    name: a
    index: b
    subindex: c
    bitlength: d
    type: e

pdo_mapping_3:
 addr: 0x1a00
 type: rx

 pdos:
  -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
  -
    name: a
    index: b
    subindex: c
    bitlength: d
    type: e

pdo_mapping_4:
 addr: 0x1a01
 type: rx

 pdos:
  -
      name: a
      index: b
      subindex: c
      bitlength: d
      type: e
  -
    name: a
    index: b
    subindex: c
    bitlength: d
    type: e

...